#include "web_console.h"

#include "esp_http_server.h"

static const char INDEX_HTML[] =
    "<!doctype html>\n"
    "<html lang='en'>\n"
    "<head>\n"
    "  <meta charset='utf-8'>\n"
    "  <meta name='viewport' content='width=device-width, initial-scale=1'>\n"
    "  <title>VibeBoard Runtime</title>\n"
    "  <style>\n"
    "    :root { color-scheme: light; --bg: rgb(244, 247, 245); --surface: rgb(255, 255, 255); --ink: rgb(24, 31, 35); --muted: rgb(92, 103, 108); --line: rgb(210, 218, 214); --accent: rgb(0, 120, 108); --accent-ink: rgb(255, 255, 255); --warn: rgb(154, 94, 0); --danger: rgb(176, 44, 38); --soft: rgb(232, 242, 239); }\n"
    "    * { box-sizing: border-box; }\n"
    "    body { margin: 0; min-height: 100dvh; background: var(--bg); color: var(--ink); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 16px; line-height: 1.5; }\n"
    "    button, input, textarea { font: inherit; }\n"
    "    button { min-height: 44px; border: 1px solid var(--line); border-radius: 8px; background: var(--surface); color: var(--ink); padding: 9px 14px; cursor: pointer; }\n"
    "    button.primary { background: var(--accent); border-color: var(--accent); color: var(--accent-ink); }\n"
    "    button.danger { color: var(--danger); border-color: rgb(229, 181, 178); }\n"
    "    button:disabled { cursor: progress; opacity: 0.58; }\n"
    "    button:focus-visible, input:focus-visible, textarea:focus-visible { outline: 3px solid rgb(106, 183, 174); outline-offset: 2px; }\n"
    "    .page { width: min(1180px, calc(100% - 28px)); margin: 0 auto; padding: 24px 0 36px; }\n"
    "    .topbar { display: flex; align-items: end; justify-content: space-between; gap: 16px; margin-bottom: 18px; }\n"
    "    .eyebrow { margin: 0 0 2px; color: var(--muted); font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0; }\n"
    "    h1, h2, h3, p { margin-top: 0; }\n"
    "    h1 { margin-bottom: 0; font-size: clamp(28px, 4vw, 40px); line-height: 1.1; letter-spacing: 0; }\n"
    "    h2 { margin-bottom: 12px; font-size: 20px; line-height: 1.25; letter-spacing: 0; }\n"
    "    h3 { margin-bottom: 6px; font-size: 17px; letter-spacing: 0; }\n"
    "    .status-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 10px; margin-bottom: 14px; }\n"
    "    .status-grid div, .panel { border: 1px solid var(--line); border-radius: 8px; background: var(--surface); }\n"
    "    .status-grid div { min-width: 0; padding: 12px; }\n"
    "    .status-grid span { display: block; color: var(--muted); font-size: 13px; }\n"
    "    .status-grid strong { display: block; overflow-wrap: anywhere; font-size: 18px; }\n"
    "    .layout { display: grid; grid-template-columns: minmax(0, 1fr) minmax(330px, 390px); gap: 14px; align-items: start; }\n"
    "    .side { display: grid; gap: 14px; }\n"
    "    .panel { padding: 16px; }\n"
    "    .section-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 8px; }\n"
    "    .apps-list { display: grid; gap: 8px; }\n"
    "    .app-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; align-items: center; padding: 12px; border: 1px solid var(--line); border-radius: 8px; background: rgb(250, 252, 251); }\n"
    "    .app-meta { min-width: 0; }\n"
    "    .app-meta strong, .app-meta span { display: block; overflow-wrap: anywhere; }\n"
    "    .app-meta span { color: var(--muted); font-size: 14px; }\n"
    "    .actions { display: flex; gap: 8px; flex-wrap: wrap; justify-content: end; }\n"
    "    label { display: grid; gap: 6px; margin-bottom: 11px; color: var(--ink); font-weight: 650; }\n"
    "    label.check { display: flex; align-items: center; gap: 9px; font-weight: 500; color: var(--muted); }\n"
    "    input, textarea { width: 100%; border: 1px solid var(--line); border-radius: 8px; background: rgb(255, 255, 255); color: var(--ink); padding: 10px 11px; }\n"
    "    textarea { resize: vertical; min-height: 128px; }\n"
    "    input[type='checkbox'] { width: 18px; height: 18px; }\n"
    "    .button-row { display: flex; gap: 8px; flex-wrap: wrap; }\n"
    "    .status-text { min-height: 24px; color: var(--muted); overflow-wrap: anywhere; }\n"
    "    .risk { color: var(--warn); background: rgb(255, 246, 229); border: 1px solid rgb(240, 213, 166); border-radius: 8px; padding: 10px; }\n"
    "    details { margin-top: 12px; }\n"
    "    summary { cursor: pointer; min-height: 44px; display: flex; align-items: center; color: var(--accent); font-weight: 700; }\n"
    "    pre { margin: 0; max-height: 260px; overflow: auto; white-space: pre-wrap; word-break: break-word; background: rgb(32, 38, 36); color: rgb(236, 244, 239); border-radius: 8px; padding: 12px; font-size: 13px; line-height: 1.45; }\n"
    "    .empty { color: var(--muted); padding: 12px; border: 1px dashed var(--line); border-radius: 8px; background: var(--soft); }\n"
    "    .log-panel { margin-top: 14px; }\n"
    "    @media (max-width: 860px) { .page { width: min(100% - 20px, 680px); padding-top: 16px; } .topbar, .section-head { align-items: stretch; flex-direction: column; } .status-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } .layout { grid-template-columns: 1fr; } .app-row { grid-template-columns: 1fr; } .actions { justify-content: start; } }\n"
    "    @media (max-width: 480px) { .status-grid { grid-template-columns: 1fr; } .button-row, .actions { flex-direction: column; } button { width: 100%; } }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class='page'>\n"
    "    <header class='topbar'>\n"
    "      <div>\n"
    "        <p class='eyebrow'>Device Console</p>\n"
    "        <h1>VibeBoard Runtime</h1>\n"
    "      </div>\n"
    "      <button id='refreshBtn' type='button'>Refresh</button>\n"
    "    </header>\n"
    "\n"
    "    <section class='status-grid' aria-label='Runtime status'>\n"
    "      <div><span>State</span><strong id='runnerState'>unknown</strong></div>\n"
    "      <div><span>Current App</span><strong id='currentApp'>none</strong></div>\n"
    "      <div><span>Apps</span><strong id='appCount'>0</strong></div>\n"
    "      <div><span>Last Result</span><strong id='lastMessage'>unknown</strong></div>\n"
    "    </section>\n"
    "\n"
    "    <main class='layout'>\n"
    "      <section class='panel'>\n"
    "        <div class='section-head'>\n"
    "          <h2>Apps</h2>\n"
    "          <button id='stopBtn' type='button'>Stop Current</button>\n"
    "        </div>\n"
    "        <div id='appsList' class='apps-list'></div>\n"
    "      </section>\n"
    "\n"
    "      <aside class='side'>\n"
    "        <section class='panel'>\n"
    "          <h2>Upload App Folder</h2>\n"
    "          <label>App ID <input id='manualAppId' type='text' autocomplete='off'></label>\n"
    "          <label>Folder <input id='folderInput' type='file' webkitdirectory multiple></label>\n"
    "          <button id='uploadBtn' class='primary' type='button'>Upload Folder</button>\n"
    "          <p id='uploadStatus' class='status-text'></p>\n"
    "        </section>\n"
    "\n"
    "        <section class='panel' id='aiPanel'>\n"
    "          <h2>AI Create App</h2>\n"
    "          <p class='risk'>Direct browser AI exposes the API key to this browser session. Use this on a trusted network. The key is not sent to the board.</p>\n"
    "          <label>OpenAI API Key <input id='apiKey' type='password' autocomplete='off'></label>\n"
    "          <label class='check'><input id='rememberKey' type='checkbox'> Remember key in this browser</label>\n"
    "          <div class='button-row'>\n"
    "            <button id='clearKeyBtn' type='button'>Clear key</button>\n"
    "          </div>\n"
    "          <label>AI Base URL <input id='aiBaseUrl' type='url' value='https://rehdasu.cn' autocomplete='off'></label>\n"
    "          <label>Model <input id='modelName' type='text' value='gpt-5.5' autocomplete='off'></label>\n"
    "          <label>New App ID <input id='aiAppId' type='text' autocomplete='off' placeholder='pomodoro'></label>\n"
    "          <label>Prompt <textarea id='aiPrompt' rows='6'></textarea></label>\n"
    "          <button id='generateBtn' class='primary' type='button'>Generate and Upload</button>\n"
    "          <p id='aiStatus' class='status-text'></p>\n"
    "          <details>\n"
    "            <summary>Generated plan</summary>\n"
    "            <pre id='planPreview'></pre>\n"
    "          </details>\n"
    "        </section>\n"
    "      </aside>\n"
    "    </main>\n"
    "\n"
    "    <section class='panel log-panel'>\n"
    "      <h2>Operation Status</h2>\n"
    "      <pre id='logOutput'>Ready.</pre>\n"
    "    </section>\n"
    "  </div>\n"
    "\n"
    "  <script>\n"
    "    const KEY_STORAGE_NAME = 'vibeboard.openai_api_key';\n"
    "    const allowedFileTypes = new Set(['lua', 'text', 'json', 'csv', 'markdown']);\n"
    "    const $ = (id) => document.getElementById(id);\n"
    "\n"
    "    function log(message) {\n"
    "      const now = new Date().toLocaleTimeString();\n"
    "      $('logOutput').textContent = '[' + now + '] ' + message + '\\n' + $('logOutput').textContent;\n"
    "    }\n"
    "\n"
    "    function setText(id, value) {\n"
    "      $(id).textContent = value == null || value === '' ? '-' : String(value);\n"
    "    }\n"
    "\n"
    "    function setBusy(button, busy) {\n"
    "      if (button) button.disabled = !!busy;\n"
    "    }\n"
    "\n"
    "    async function fetchJson(path) {\n"
    "      const response = await fetch(path, { headers: { Accept: 'application/json' } });\n"
    "      const text = await response.text();\n"
    "      if (!response.ok) throw new Error(response.status + ' ' + text);\n"
    "      return text ? JSON.parse(text) : {};\n"
    "    }\n"
    "\n"
    "    async function postJson(path) {\n"
    "      const response = await fetch(path, { method: 'POST', headers: { Accept: 'application/json' } });\n"
    "      const text = await response.text();\n"
    "      if (!response.ok) throw new Error(response.status + ' ' + text);\n"
    "      return text ? JSON.parse(text) : {};\n"
    "    }\n"
    "\n"
    "    async function discardAfterFailure(appId) {\n"
    "      try {\n"
    "        await postJson('/discard?app=' + encodeURIComponent(appId));\n"
    "      } catch (discardError) {\n"
    "        log('Discard after failure also failed: ' + discardError.message);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    async function refreshRuntime() {\n"
    "      try {\n"
    "        const status = await fetchJson('/status');\n"
    "        const apps = await fetchJson('/apps');\n"
    "        renderStatus(status, apps.apps || []);\n"
    "        renderApps(apps.apps || [], status);\n"
    "        log('Runtime refreshed.');\n"
    "      } catch (error) {\n"
    "        log('Refresh failed: ' + error.message);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function renderStatus(status, apps) {\n"
    "      setText('runnerState', status.state || 'unknown');\n"
    "      setText('currentApp', status.running ? status.current_app : 'none');\n"
    "      setText('appCount', status.app_count ?? apps.length);\n"
    "      setText('lastMessage', status.last_message || status.install || (status.sd ? 'ok' : 'sd unavailable'));\n"
    "    }\n"
    "\n"
    "    function renderApps(apps, status) {\n"
    "      const list = $('appsList');\n"
    "      list.textContent = '';\n"
    "      if (!apps.length) {\n"
    "        const empty = document.createElement('div');\n"
    "        empty.className = 'empty';\n"
    "        empty.textContent = 'No apps found on SD.';\n"
    "        list.appendChild(empty);\n"
    "        return;\n"
    "      }\n"
    "      for (const app of apps) {\n"
    "        const row = document.createElement('article');\n"
    "        row.className = 'app-row';\n"
    "        const meta = document.createElement('div');\n"
    "        meta.className = 'app-meta';\n"
    "        const title = document.createElement('strong');\n"
    "        title.textContent = app.name || app.id;\n"
    "        const detail = document.createElement('span');\n"
    "        detail.textContent = app.id + ' / ' + (app.entry || 'main.lua');\n"
    "        meta.append(title, detail);\n"
    "        const actions = document.createElement('div');\n"
    "        actions.className = 'actions';\n"
    "        const launch = document.createElement('button');\n"
    "        launch.type = 'button';\n"
    "        launch.textContent = status.running && status.current_app === app.id ? 'Running' : 'Launch';\n"
    "        launch.disabled = status.running && status.current_app === app.id;\n"
    "        launch.addEventListener('click', async () => {\n"
    "          setBusy(launch, true);\n"
    "          try {\n"
    "            await postJson('/launch?app=' + encodeURIComponent(app.id));\n"
    "            log('Launched ' + app.id + '.');\n"
    "            await refreshRuntime();\n"
    "          } catch (error) {\n"
    "            log('Launch failed for ' + app.id + ': ' + error.message);\n"
    "          } finally {\n"
    "            setBusy(launch, false);\n"
    "          }\n"
    "        });\n"
    "        const remove = document.createElement('button');\n"
    "        remove.type = 'button';\n"
    "        remove.className = 'danger';\n"
    "        remove.textContent = 'Delete';\n"
    "        remove.addEventListener('click', async () => {\n"
    "          if (!confirm('Delete app ' + app.id + '?')) return;\n"
    "          setBusy(remove, true);\n"
    "          try {\n"
    "            await postJson('/delete?app=' + encodeURIComponent(app.id));\n"
    "            log('Deleted ' + app.id + '.');\n"
    "            await refreshRuntime();\n"
    "          } catch (error) {\n"
    "            log('Delete failed for ' + app.id + ': ' + error.message);\n"
    "          } finally {\n"
    "            setBusy(remove, false);\n"
    "          }\n"
    "        });\n"
    "        actions.append(launch, remove);\n"
    "        row.append(meta, actions);\n"
    "        list.appendChild(row);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function validateAppId(appId) {\n"
    "      if (!/^[A-Za-z0-9_-]+$/.test(appId)) throw new Error('App ID may only contain letters, digits, _ and -.');\n"
    "    }\n"
    "\n"
    "    function validateRelativePath(path) {\n"
    "      if (!path || path.startsWith('/') || path.includes('..') || path.includes('\\\\')) {\n"
    "        throw new Error('Unsafe path: ' + path);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function encodePath(path) {\n"
    "      return path.split('/').map(encodeURIComponent).join('/');\n"
    "    }\n"
    "\n"
    "    function commonRoot(files) {\n"
    "      const roots = Array.from(files).map((file) => (file.webkitRelativePath || file.name).split('/')[0]).filter(Boolean);\n"
    "      return roots.length > 0 && roots.every((root) => root === roots[0]) ? roots[0] : '';\n"
    "    }\n"
    "\n"
    "    function relativePathForFile(file, rootPrefix) {\n"
    "      let path = file.webkitRelativePath || file.name;\n"
    "      if (rootPrefix && path.startsWith(rootPrefix + '/')) path = path.slice(rootPrefix.length + 1);\n"
    "      validateRelativePath(path);\n"
    "      return path;\n"
    "    }\n"
    "\n"
    "    async function uploadFilesForApp(appId, files) {\n"
    "      validateAppId(appId);\n"
    "      if (!files.length) throw new Error('Choose an app folder first.');\n"
    "      const rootPrefix = commonRoot(files);\n"
    "      await postJson('/discard?app=' + encodeURIComponent(appId));\n"
    "      try {\n"
    "        let sent = 0;\n"
    "        for (const file of files) {\n"
    "          const rel = relativePathForFile(file, rootPrefix);\n"
    "          const stageUrl = '/stage?app=' + encodeURIComponent(appId) + '&path=' + encodePath(rel);\n"
    "          const response = await fetch(stageUrl, { method: 'POST', body: file });\n"
    "          if (!response.ok) throw new Error(response.status + ' ' + await response.text());\n"
    "          sent += 1;\n"
    "          $('uploadStatus').textContent = 'Uploaded ' + sent + ' of ' + files.length + ' files.';\n"
    "        }\n"
    "        await postJson('/commit?app=' + encodeURIComponent(appId));\n"
    "        await refreshRuntime();\n"
    "      } catch (error) {\n"
    "        await discardAfterFailure(appId);\n"
    "        throw error;\n"
    "      }\n"
    "    }\n"
    "\n"
    "    async function uploadManualFolder() {\n"
    "      const button = $('uploadBtn');\n"
    "      setBusy(button, true);\n"
    "      try {\n"
    "        const files = Array.from($('folderInput').files || []);\n"
    "        const rootPrefix = commonRoot(files);\n"
    "        const appId = $('manualAppId').value.trim() || rootPrefix;\n"
    "        $('manualAppId').value = appId;\n"
    "        $('uploadStatus').textContent = 'Uploading...';\n"
    "        await uploadFilesForApp(appId, files);\n"
    "        $('uploadStatus').textContent = 'Uploaded and committed ' + appId + '.';\n"
    "        log('Uploaded and committed ' + appId + '.');\n"
    "      } catch (error) {\n"
    "        $('uploadStatus').textContent = error.message;\n"
    "        log('Upload failed: ' + error.message);\n"
    "      } finally {\n"
    "        setBusy(button, false);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function loadStoredKey() {\n"
    "      const stored = localStorage.getItem(KEY_STORAGE_NAME);\n"
    "      if (stored) {\n"
    "        $('apiKey').value = stored;\n"
    "        $('rememberKey').checked = true;\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function persistKeyPreference() {\n"
    "      const key = $('apiKey').value.trim();\n"
    "      if ($('rememberKey').checked && key) {\n"
    "        localStorage.setItem(KEY_STORAGE_NAME, key);\n"
    "      } else {\n"
    "        localStorage.removeItem(KEY_STORAGE_NAME);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function clearStoredKey() {\n"
    "      localStorage.removeItem(KEY_STORAGE_NAME);\n"
    "      $('apiKey').value = '';\n"
    "      $('rememberKey').checked = false;\n"
    "      log('OpenAI API key cleared from this browser.');\n"
    "    }\n"
    "\n"
    "    function cleanInfoValue(value) {\n"
    "      return String(value || '').replace(/[\\r\\n]/g, ' ').trim();\n"
    "    }\n"
    "\n"
    "    function synthesizeAppInfo(plan) {\n"
    "      const capabilities = Array.isArray(plan.app.capabilities) ? plan.app.capabilities.map(cleanInfoValue).filter(Boolean).join(',') : '';\n"
    "      return [\n"
    "        'name = ' + cleanInfoValue(plan.app.name),\n"
    "        'entry = ' + cleanInfoValue(plan.app.entry),\n"
    "        'description = ' + cleanInfoValue(plan.app.description),\n"
    "        capabilities ? 'capabilities = ' + capabilities : '',\n"
    "        ''\n"
    "      ].filter(Boolean).join('\\n');\n"
    "    }\n"
    "\n"
    "    function validatePlan(plan) {\n"
    "      if (!plan || plan.kind !== 'app_plan') throw new Error('AI did not return an app plan.');\n"
    "      if (!plan.app || !plan.app.name || !plan.app.entry || !plan.app.description) throw new Error('Plan is missing app metadata.');\n"
    "      validateRelativePath(plan.app.entry);\n"
    "      if (!Array.isArray(plan.files)) throw new Error('Plan files must be an array.');\n"
    "      let hasEntry = false;\n"
    "      for (const file of plan.files) {\n"
    "        validateRelativePath(file.path);\n"
    "        if (!allowedFileTypes.has(file.type)) throw new Error('Unsupported text file type: ' + file.type);\n"
    "        if (file.path === plan.app.entry && file.type === 'lua') hasEntry = true;\n"
    "        if (typeof file.content !== 'string') throw new Error('File content must be text: ' + file.path);\n"
    "      }\n"
    "      if (!hasEntry) throw new Error('Plan does not include the Lua entry file.');\n"
    "    }\n"
    "\n"
    "    function extractResponseText(payload) {\n"
    "      if (payload.output_text) return payload.output_text;\n"
    "      for (const item of payload.output || []) {\n"
    "        for (const content of item.content || []) {\n"
    "          if ((content.type === 'output_text' || content.type === 'text') && content.text) return content.text;\n"
    "        }\n"
    "      }\n"
    "      return '';\n"
    "    }\n"
    "\n"
    "    function extractAiBaseUrl(rawValue) {\n"
    "      const value = String(rawValue || '').trim();\n"
    "      if (!value) throw new Error('AI Base URL is required.');\n"
    "      const match = value.match(/https?:\\/\\/[^\\s\\\"'<>]+/);\n"
    "      const candidate = match ? match[0] : value;\n"
    "      let url;\n"
    "      try {\n"
    "        url = new URL(candidate);\n"
    "      } catch (error) {\n"
    "        throw new Error('AI Base URL must be a valid http(s) URL.');\n"
    "      }\n"
    "      if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new Error('AI Base URL must use http or https.');\n"
    "      return url.href.replace(/\\/+$/, '').replace(/\\/v1\\/responses\\/?$/, \"\").replace(/\\/v1\\/?$/, \"\");\n"
    "    }\n"
    "\n"
    "    function normalizeAiBaseUrl(baseUrl) {\n"
    "      return extractAiBaseUrl(baseUrl);\n"
    "    }\n"
    "\n"
    "    function buildAiResponsesUrl(baseUrl) {\n"
    "      return normalizeAiBaseUrl(baseUrl) + '/v1/responses';\n"
    "    }\n"
    "\n"
    "    async function generatePlanWithOpenAI(apiKey, baseUrl, model, prompt, appId) {\n"
    "      const requestUrl = buildAiResponsesUrl(baseUrl);\n"
    "      let response;\n"
    "      try {\n"
    "        response = await fetch(requestUrl, {\n"
    "          method: 'POST',\n"
    "          headers: {\n"
    "            'Authorization': 'Bearer ' + apiKey,\n"
    "            'Content-Type': 'application/json'\n"
    "          },\n"
    "          body: JSON.stringify({\n"
    "            model,\n"
    "            input: [\n"
    "              {\n"
    "                role: 'system',\n"
    "                content: 'Generate one VibeBoard Lua/LVGL app package plan as JSON. Use simple text-only files. Return runtime_update_required when firmware, drivers, BLE, partitions, sdkconfig, native modules, binary assets, or unavailable LVGL bindings are needed.'\n"
    "              },\n"
    "              {\n"
    "                role: 'user',\n"
    "                content: 'App ID: ' + appId + '\\nRequest: ' + prompt\n"
    "              }\n"
    "            ],\n"
    "            text: {\n"
    "              format: {\n"
    "                type: 'json_schema',\n"
    "                name: 'vibeboard_app_plan',\n"
    "                strict: true,\n"
    "                schema: {\n"
    "                  type: 'object',\n"
    "                  additionalProperties: false,\n"
    "                  required: ['kind', 'reason', 'app', 'files'],\n"
    "                  properties: {\n"
    "                    kind: { type: 'string', enum: ['app_plan', 'runtime_update_required'] },\n"
    "                    reason: { anyOf: [{ type: 'string' }, { type: 'null' }] },\n"
    "                    app: {\n"
    "                      anyOf: [\n"
    "                        { type: 'null' },\n"
    "                        {\n"
    "                          type: 'object',\n"
    "                          additionalProperties: false,\n"
    "                          required: ['name', 'entry', 'description', 'capabilities'],\n"
    "                          properties: {\n"
    "                            name: { type: 'string' },\n"
    "                            entry: { type: 'string' },\n"
    "                            description: { type: 'string' },\n"
    "                            capabilities: { type: 'array', items: { type: 'string' } }\n"
    "                          }\n"
    "                        }\n"
    "                      ]\n"
    "                    },\n"
    "                    files: {\n"
    "                      anyOf: [\n"
    "                        { type: 'null' },\n"
    "                        {\n"
    "                          type: 'array',\n"
    "                          items: {\n"
    "                            type: 'object',\n"
    "                            additionalProperties: false,\n"
    "                            required: ['path', 'type', 'content'],\n"
    "                            properties: {\n"
    "                              path: { type: 'string' },\n"
    "                              type: { type: 'string', enum: ['lua', 'text', 'json', 'csv', 'markdown'] },\n"
    "                              content: { type: 'string' }\n"
    "                            }\n"
    "                          }\n"
    "                        }\n"
    "                      ]\n"
    "                    }\n"
    "                  }\n"
    "                }\n"
    "              }\n"
    "            }\n"
    "          })\n"
    "        });\n"
    "      } catch (error) {\n"
    "        throw new Error('AI request failed for ' + requestUrl + ': ' + error.message);\n"
    "      }\n"
    "      const body = await response.text();\n"
    "      let payload;\n"
    "      try {\n"
    "        payload = body ? JSON.parse(body) : {};\n"
    "      } catch (error) {\n"
    "        throw new Error('AI request returned non-JSON ' + response.status + ' from ' + requestUrl + ': ' + body.slice(0, 180));\n"
    "      }\n"
    "      if (!response.ok) {\n"
    "        const upstreamMessage = payload.error?.message || payload.message || payload.code || JSON.stringify(payload);\n"
    "        throw new Error('AI request failed ' + response.status + ' for ' + requestUrl + ': ' + upstreamMessage);\n"
    "      }\n"
    "      const text = extractResponseText(payload);\n"
    "      if (!text) throw new Error('OpenAI response did not include output_text.');\n"
    "      try {\n"
    "        return JSON.parse(text);\n"
    "      } catch (error) {\n"
    "        throw new Error('AI response was not valid app-plan JSON: ' + error.message);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function filesFromPlan(plan) {\n"
    "      const files = plan.files.filter((file) => file.path !== 'app.info').map((file) => ({ path: file.path, content: file.content }));\n"
    "      files.unshift({ path: 'app.info', content: synthesizeAppInfo(plan) });\n"
    "      return files;\n"
    "    }\n"
    "\n"
    "    async function uploadGeneratedPlan(appId, plan) {\n"
    "      const files = filesFromPlan(plan);\n"
    "      await postJson('/discard?app=' + encodeURIComponent(appId));\n"
    "      try {\n"
    "        let sent = 0;\n"
    "        for (const file of files) {\n"
    "          const stageUrl = '/stage?app=' + encodeURIComponent(appId) + '&path=' + encodePath(file.path);\n"
    "          const response = await fetch(stageUrl, { method: 'POST', body: file.content });\n"
    "          if (!response.ok) throw new Error(response.status + ' ' + await response.text());\n"
    "          sent += 1;\n"
    "          $('aiStatus').textContent = 'Uploaded ' + sent + ' of ' + files.length + ' generated files.';\n"
    "        }\n"
    "        await postJson('/commit?app=' + encodeURIComponent(appId));\n"
    "        await refreshRuntime();\n"
    "      } catch (error) {\n"
    "        await discardAfterFailure(appId);\n"
    "        throw error;\n"
    "      }\n"
    "    }\n"
    "\n"
    "    async function createAppWithAI() {\n"
    "      const button = $('generateBtn');\n"
    "      setBusy(button, true);\n"
    "      try {\n"
    "        const apiKey = $('apiKey').value.trim();\n"
    "        const baseUrl = $('aiBaseUrl').value.trim();\n"
    "        const model = $('modelName').value.trim();\n"
    "        const appId = $('aiAppId').value.trim();\n"
    "        const prompt = $('aiPrompt').value.trim();\n"
    "        if (!apiKey) throw new Error('OpenAI API Key is required.');\n"
    "        if (!baseUrl) throw new Error('AI Base URL is required.');\n"
    "        if (!model) throw new Error('Model is required.');\n"
    "        if (!prompt) throw new Error('Prompt is required.');\n"
    "        validateAppId(appId);\n"
    "        persistKeyPreference();\n"
    "        $('aiStatus').textContent = 'Generating app plan...';\n"
    "        const plan = await generatePlanWithOpenAI(apiKey, baseUrl, model, prompt, appId);\n"
    "        $('planPreview').textContent = JSON.stringify(plan, null, 2);\n"
    "        if (plan.kind === 'runtime_update_required') {\n"
    "          $('aiStatus').textContent = plan.reason || 'Runtime update required.';\n"
    "          log('AI reported runtime_update_required.');\n"
    "          return;\n"
    "        }\n"
    "        validatePlan(plan);\n"
    "        $('aiStatus').textContent = 'Uploading generated app...';\n"
    "        await uploadGeneratedPlan(appId, plan);\n"
    "        $('aiStatus').textContent = 'Generated and committed ' + appId + '.';\n"
    "        log('Generated and committed ' + appId + '.');\n"
    "      } catch (error) {\n"
    "        const message = error.message || String(error);\n"
    "        $('aiStatus').textContent = message;\n"
    "        log('AI create failed: ' + message);\n"
    "      } finally {\n"
    "        setBusy(button, false);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    $('refreshBtn').addEventListener('click', refreshRuntime);\n"
    "    $('stopBtn').addEventListener('click', async () => {\n"
    "      setBusy($('stopBtn'), true);\n"
    "      try {\n"
    "        await postJson('/stop');\n"
    "        log('Stop requested.');\n"
    "        await refreshRuntime();\n"
    "      } catch (error) {\n"
    "        log('Stop failed: ' + error.message);\n"
    "      } finally {\n"
    "        setBusy($('stopBtn'), false);\n"
    "      }\n"
    "    });\n"
    "    $('uploadBtn').addEventListener('click', uploadManualFolder);\n"
    "    $('generateBtn').addEventListener('click', createAppWithAI);\n"
    "    $('clearKeyBtn').addEventListener('click', clearStoredKey);\n"
    "    $('rememberKey').addEventListener('change', persistKeyPreference);\n"
    "    loadStoredKey();\n"
    "    refreshRuntime();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

static esp_err_t root_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    httpd_resp_set_hdr(req, "X-Content-Type-Options", "nosniff");
    return httpd_resp_sendstr(req, INDEX_HTML);
}

esp_err_t vb_web_console_register(httpd_handle_t server)
{
    if (server == NULL) {
        return ESP_ERR_INVALID_ARG;
    }

    const httpd_uri_t root_uri = {
        .uri = "/",
        .method = HTTP_GET,
        .handler = root_handler,
        .user_ctx = NULL,
    };
    return httpd_register_uri_handler(server, &root_uri);
}
